---
title: "Viz_I"
author: "Briana Lettsome"
date: "September 27, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)

```

```{r}
library(rnoaa)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

```{r}
weather_df %>% View
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r}
plot_weather = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) 

plot_weather + geom_point()
```

More plot options
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

Add geom 
```{r}

```

A more interesting plot

```{r}
ggplot(weather_df, aes(x = date, y = tmax))
  geom_point()
```

Histograms!!

```{r}
ggplot(weather_df, aes(x = tmax)) +
  geom_histogram()
```

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_histogram() 
```

Density plot - A smoothed out histogram

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.5) 
```

Box plots!!

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) +
  geom_boxplot() 
```

Violin pots!

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) +
  geom_violin() 

```


```{r}
ggplot(weather_df, aes(x = tmax, y = name)) +
  geom_density_ridges(scale = 0.85) 
```